import h5py
import numpy as np

def load_h5py(path_to_hdf5):

    file = h5py.File(path_to_hdf5, "r")
    ids = file["ids"][:]
    data = file["signals"][:]

    return ids, data

def write_h5py(file_name, data, ids=None):
    """
    This function was generated by Sonnet 4.6
    """

    if ids is not None:
        with h5py.File(f"{file_name}.hdf5", "w") as f:
            f.create_dataset("ids", data=np.array(ids, dtype=np.int32))
            f.create_dataset("signals", data=np.array(data), compression="gzip")
    else:
        with h5py.File(f"{file_name}.hdf5", "w") as f:
            f.create_dataset("tracings", data=np.array(data), compression="gzip")
