"""
This file was generated by Sonnet 4.6
"""

import os

import dotenv
import streamlit.components.v1 as components

# needs to also sit behind authelia!!!
dotenv.load_dotenv()
FLASK_BASE = os.environ["CF_RECORDER_FLASK_BASE"]
# "https://yourdomain.com/recorder-api"

# The one thing you do need to make sure is that your reverse proxy (nginx/Traefik/etc.)
# has a rule that maps /recorder-api to 127.0.0.1:5050.
# That config is what connects the two together behind the scenes.


def recorder_button(user):
    challenge = os.environ["CF_SERVER_SECRET"]
    components.html(
        f"""
        <button id="btn" onclick="openRecorder()"
            style="background:#ff4b4b; color:white; border:none; padding:10px 20px;
                   border-radius:6px; cursor:pointer; font-size:16px;">
            ⚙️ Screen Recording Settings
        </button>

        <script>
        const btn = document.getElementById('btn');
        if (sessionStorage.getItem('recorder_opened') === 'true') {{
            btn.style.background = '#555';
        }}
        function openRecorder() {{
            const p = window.open(
                '{FLASK_BASE}/recorder?user={user}&challenge={challenge}',
                'recorder',
                'width=350,height=150,top=100,left=100'
            );
            if (p) {{
                p.focus();
                sessionStorage.setItem('recorder_opened', 'true');
                btn.style.background = '#555';
            }}
        }}
        </script>
    """,
        height=50,
    )


def stop_recording(user):
    challenge = os.environ["CF_SERVER_SECRET"]
    components.html(
        f"""
        <script>
        fetch('{FLASK_BASE}/signal-stop?user={user}&challenge={challenge}', {{ method: 'POST' }});
        sessionStorage.removeItem('recorder_opened');
        </script>
    """,
        height=1,
    )
