import streamlit as st
import plotly.graph_objects as go
import pandas as pd
from collections import Counter

LEADS = ["DI", "DII", "DIII", "AVR", "AVL", "AVF", "V1", "V2", "V3", "V4", "V5", "V6"]
LEAD_NAMES = ["DI", "DII", "DIII", "aVR", "aVL", "aVF", "V1", "V2", "V3", "V4", "V5", "V6"]

@st.cache_data
def render_figure(lead, name):
    """
    This function was generated by Sonnet 4.6
    """
    SAMPLING_RATE = 400
    fig = go.Figure()
    t = [i / SAMPLING_RATE for i in range(len(lead))]
    fig.add_trace(go.Scatter(
        x=t,
        y=lead,
        mode="lines",
        line=dict(color="#00ff88", width=1.2),
    ))
    fig.update_layout(
        title=dict(text=name, font=dict(color="white")),
        xaxis_title="Time (s)",
        yaxis_title="Amplitude (mV)",
        plot_bgcolor="#0e1117",
        paper_bgcolor="#0e1117",
        font_color="white",
        xaxis=dict(showgrid=True, gridcolor="#1f2937", zeroline=False),
        yaxis=dict(showgrid=True, gridcolor="#1f2937", zeroline=False),
        height=300,
        margin=dict(l=40, r=20, t=40, b=40),
    )
    return fig

def set_comparison(idx):
    st.session_state.comparison_index = idx

@st.cache_data
def fetch_page(index: int):
    return pd.read_parquet(f"data/{index}.parquet", engine="pyarrow")

@st.fragment
def comparison_per_signal():
    signals = fetch_page(st.session_state.page_index)
    
    original = signals.iloc[0]
    comp = {1: signals.iloc[1], 2: signals.iloc[2], 3: signals.iloc[3]}[st.session_state.comparison_index]

    _, col1, col2, col3, _ = st.columns([2, 1, 1, 1, 2])
    with col1:
        st.button("Comparison 1", type="primary" if st.session_state.comparison_index == 1 else "secondary",
                  on_click=set_comparison, args=(1,), use_container_width=True)
    with col2:
        st.button("Comparison 2", type="primary" if st.session_state.comparison_index == 2 else "secondary",
                  on_click=set_comparison, args=(2,), use_container_width=True)
    with col3:
        st.button("Comparison 3", type="primary" if st.session_state.comparison_index == 3 else "secondary",
                  on_click=set_comparison, args=(3,), use_container_width=True)

    st.divider()

    for lead, name in zip(LEADS, LEAD_NAMES):
        st.markdown(f"**{name}**")
        col_left, col_right = st.columns(2)
        with col_left:
            st.plotly_chart(render_figure(original[lead], "Original"), use_container_width=True, key=f"{lead}_orig")
        with col_right:
            st.plotly_chart(render_figure(comp[lead], f"Comparison {st.session_state.comparison_index}"), use_container_width=True, key=f"{lead}_comp{st.session_state.comparison_index}")


def expender_style():
    """
    This function was generated by Sonnet 4.6
    """
    st.markdown(
        """
        <style>
            details {
                border: 2px solid #0e1117 !important;
                border-radius: 4px !important;
                background-color: #0e1117 !important;
            }
            details summary {
                position: relative !important;
                background-color: #0e1117 !important;
                border-bottom: 2px solid #3d4147 !important;  /* line between header and content */
            }
            details summary p {
                font-size: 22px !important;
                font-weight: bold !important;
                position: absolute !important;
                left: 50% !important;
                top: 50% !important;
                transform: translate(-50%, -50%) !important;
                color: white !important;
            }
            [data-testid="stIconMaterial"] {
                color: white !important;
            }
        </style>
        """,
        unsafe_allow_html=True
    )

@st.fragment
def display_lead(name, on, lead, original, comp_1, comp_2, comp_3):
    with st.expander(name, expanded=True): 
        st.markdown('<div class="content-box">', unsafe_allow_html=True)
        if on:
            st.plotly_chart(render_figure(original[lead], "Original"), use_container_width=True, key=f"{lead}_orig")
            st.plotly_chart(render_figure(comp_1[lead], f"Comparison 1"), use_container_width=True, key=f"{lead}_comp1")
            st.plotly_chart(render_figure(comp_2[lead], f"Comparison 2"), use_container_width=True, key=f"{lead}_comp2")
            st.plotly_chart(render_figure(comp_3[lead], f"Comparison 3"), use_container_width=True, key=f"{lead}_comp3")
        
        else:
            col1, col2 = st.columns([1, 1])
            with col1:
                st.plotly_chart(render_figure(original[lead], "Original"), use_container_width=True, key=f"{lead}_orig")
                st.plotly_chart(render_figure(comp_2[lead], f"Comparison 2"), use_container_width=True, key=f"{lead}_comp2")
            with col2:
                st.plotly_chart(render_figure(comp_1[lead], f"Comparison 1"), use_container_width=True, key=f"{lead}_comp1")
                st.plotly_chart(render_figure(comp_3[lead], f"Comparison 3"), use_container_width=True, key=f"{lead}_comp3")

def save_selection(lead):
    st.session_state[f"saved_{lead}"] = st.session_state[f"lead_{lead}_{st.session_state.page_index}"]

@st.fragment
def display_lead_selection(name, lead):
    """
    This function was generated by Sonnet 4.6
    """
    st.markdown("""
    <style>
        div[data-testid="stElementContainer"][class*="st-key-lead_"] {
            width: 100% !important;
            display: flex !important;
            justify-content: center !important;
        }
        div[data-testid="stButtonGroup"] button {
            padding: 0.75rem 2rem !important;
            height: auto !important;
        }
        </style>
    """, unsafe_allow_html=True)
    
  
    text = f"<b> Which comparison signal is most similar to the original signal for lead {name} </b>"
    st.markdown(f'<p style="font-size: 20px; text-align: center;">{text}</p>', unsafe_allow_html=True)
    st.segmented_control(
        "",
        options=["Comparison 1", "Comparison 2", "Comparison 3"],
        key=f"lead_{lead}_{st.session_state.page_index}",
        on_change=save_selection,
        args=(lead,)
    )

@st.fragment
def display_summary():
    """
    This function was generated by Sonnet 4.6
    """
    counts = Counter(
        st.session_state.get(f"saved_{lead}")
        for lead in LEADS
        if st.session_state.get(f"saved_{lead}") is not None
    )
    st.write("Press the 'Refresh Summary' button to see how often each comparison signal was the most similar to the original signal.")
    col_1, col3 = st.columns([1,2])
    with col_1:
        if st.button("Refresh Summary", help="Click to get the updated counts"):
            total = sum(counts.values())
            if total < len(LEADS):
                st.warning(f"Only {total} out of {len(LEADS)} leads have been selected.")

    with col3:
        st.dataframe(
            {"ECG": ["Comparison 1", "Comparison 2", "Comparison 3"],
            "Count": [counts.get(comp, 0) for comp in ["Comparison 1", "Comparison 2", "Comparison 3"]]},
            hide_index=True,
            use_container_width=True
        )

def comparison_per_lead():

    on = st.toggle("Detailed View")

    st.divider()

    expender_style()
        
    signals = fetch_page(st.session_state.page_index)
    original = signals.iloc[0]
    comp_1 = signals.iloc[1]
    comp_2 = signals.iloc[2]
    comp_3 = signals.iloc[3]

    
    for lead, name in zip(LEADS, LEAD_NAMES):
        display_lead(name, on, lead, original, comp_1, comp_2, comp_3)
        display_lead_selection(name, lead)


