"""
This file was generated by GPT-5.3 & Sonnet 4.6
Filter PTB-XL dataset to only include abnormalities that are also predicted by automatic-ecg-diagnosis model
"""
from pathlib import Path
import pandas as pd
import ast

TARGET = {"1AVB", "NORM", "CRBBB", "CLBBB", "AFIB", "STACH", "SBRAD", "SR"}

def extract_labels(scp):
    labels = []
    if scp.get("1AVB", 0) == 100:
        labels.append("1AVB")
    if scp.get("NORM", 0) == 100:
        labels.append("NORM")
    if scp.get("CRBBB", 0) == 100:
        labels.append("CRBBB")
    if scp.get("CLBBB", 0) == 100:
        labels.append("CLBBB")
    if "AFIB" in scp:
        labels.append("AFIB")
    if "STACH" in scp:
        labels.append("STACH")
    if "SBRAD" in scp:
        labels.append("SBRAD")
    return labels if labels else None

ZERO_OK = {"SR", "AFIB", "STACH", "SBRAD"}

def is_pure(scp):
    for k, v in scp.items():
        if k in ZERO_OK:
            continue
        if v != 100:
            return False

    active = {k for k, v in scp.items() if v == 100 or k in ZERO_OK}
    if not active.issubset(TARGET):
        return False

    if scp.get("NORM", 0) == 100 and len(active) > 1:
        return False

    return True




def filter_ptbxl_entries(csv_path: Path) -> pd.DataFrame:
    """Select the relevant ptbxl ECG's """
    df = pd.read_csv(csv_path)
    df["scp_codes"] = df["scp_codes"].apply(ast.literal_eval)

    noise_cols = ["static_noise", "burst_noise", "electrodes_problems", "extra_beats", "pacemaker"]

    result = df[
        (df["validated_by_human"] == True) &
        (df[noise_cols].isnull().all(axis=1)) &
        (df["scp_codes"].apply(lambda scp: isinstance(scp, dict) and (
            scp.get("1AVB", 0) == 100 or scp.get("NORM", 0) == 100 or
            scp.get("CRBBB", 0) == 100 or scp.get("CLBBB", 0) == 100 or
            "AFIB" in scp or "STACH" in scp or "SBRAD" in scp
        ))) &
        (df["scp_codes"].apply(lambda scp: isinstance(scp, dict) and is_pure(scp)))
    ][["ecg_id", "age", "sex", "scp_codes", "filename_hr"]]

    result["labels"] = result["scp_codes"].apply(extract_labels)

    result = result.drop(columns=["scp_codes"])

    return result
    #result.to_csv("datasets/filter_ptbxl_datafile", index=False)


if __name__ == "__main__":
    df = pd.read_csv("datasets/ptbxl_database.csv")
    df["scp_codes"] = df["scp_codes"].apply(ast.literal_eval)

    noise_cols = ["static_noise", "burst_noise", "electrodes_problems", "extra_beats", "pacemaker"]

    result = df[
        (df["validated_by_human"] == True) &
        (df[noise_cols].isnull().all(axis=1)) &
        (df["scp_codes"].apply(lambda scp: isinstance(scp, dict) and (
            scp.get("1AVB", 0) == 100 or scp.get("NORM", 0) == 100 or
            scp.get("CRBBB", 0) == 100 or scp.get("CLBBB", 0) == 100 or
            "AFIB" in scp or "STACH" in scp or "SBRAD" in scp
        ))) &
        (df["scp_codes"].apply(lambda scp: isinstance(scp, dict) and is_pure(scp)))
    ][["ecg_id", "age", "sex", "scp_codes", "filename_hr"]]

    result["labels"] = result["scp_codes"].apply(extract_labels)

    result = result.drop(columns=["scp_codes"])

    result.to_csv("datasets/filtered_ecg_experiment_2.csv", index=False)
