from pathlib import Path
from loguru import logger
import pandas as pd
from tqdm import tqdm
import numpy as np
from clinical_friction.database.useful_queries import get_ecg_signals
from clinical_friction.helpers.remove_padding import remove_zero_padding

LEADS = ["DI", "DII", "DIII", "AVR", "AVL", "AVF", "V1", "V2", "V3", "V4", "V5", "V6"]
MEASURES = ["DTW", "In_Population", "Out_Population"]

def load_best_match(path, query_id):
    df = pd.read_csv(path / f"{query_id}.csv", header=None)
    return df.loc[df[0] == query_id, 1].iloc[0]


def build_similarity_table(sample_ids: list[int], dst_dir: Path, measures: list[str]):
    df = pd.DataFrame(index=sample_ids)
    df.index.name = "id"
    for measure in measures:
        path = dst_dir / measure
        path.mkdir(exist_ok=True)
        df[measure] = {id_: load_best_match(path, id_) for id_ in sample_ids}
    return df


def fetch_ecg_dataframe(unique_ids):
    ecgs = get_ecg_signals(unique_ids.tolist(), filtered=True)
    rows = []
    for row in ecgs.itertuples(index=False):
        signal = remove_zero_padding(row.signal)
        entry = {"id": row.id}
        for i, lead in enumerate(LEADS):
            entry[lead] = signal[i]
        rows.append(entry)
    return pd.DataFrame(rows)


def shuffle_and_save(df_similarity: pd.DataFrame, df_ecg: pd.DataFrame, output_dir: Path):
    """
    This function was generated by Sonnet 4.6
    """

    df_shuffled = df_similarity.sample(frac=1)
    shuffled_ids = df_shuffled.index.tolist()
    cols = df_shuffled.columns.tolist()

    shuffled_rows = []
    column_orders = []

    for i, (sample_id, row) in enumerate(df_shuffled.iterrows()):
        # randomly permute the 3 measures for this row
        perm = np.random.permutation(len(cols))
        shuffled_rows.append(row.values[perm])
        column_orders.append([cols[i] for i in perm])

        # build parquet: original ECG + the 3 comparison ECGs in shuffled order
        match_ids = row.values[perm]

        frames = [
            df_ecg[df_ecg["id"] == sample_id],
            *[df_ecg[df_ecg["id"] == mid] for mid in match_ids],
        ]
        pd.concat(frames, ignore_index=True).to_parquet(
            output_dir / f"{i}.parquet", engine="pyarrow", index=False
        )

    df_out = pd.DataFrame(shuffled_rows, index=shuffled_ids)
    df_out.index.name = "id"
    df_out.to_csv(output_dir / "data_shuffled.csv")

    pd.DataFrame({"id": shuffled_ids, "column_order": column_orders}).to_csv(
        output_dir / "mapping.csv", index=False
    )


def build_save_table(samples: list[int], dst_dir: Path, website_dir: Path):

    df_similarity = build_similarity_table(samples, dst_dir, MEASURES)
    df_similarity.to_csv(dst_dir / "summary.csv")

    all_ids = pd.unique(np.concatenate([df_similarity.values.ravel(), samples]))
    df_ecg = fetch_ecg_dataframe(all_ids)

    shuffle_and_save(df_similarity, df_ecg, website_dir)

if __name__ == "__main__":
    main()
