import pandas as pd
import numpy as np
from clinical_friction.database.useful_queries import get_ecg_signals
from clinical_friction.helpers.remove_padding import remove_zero_padding

LEADS = ["DI", "DII", "DIII", "AVR", "AVL", "AVF", "V1", "V2", "V3", "V4", "V5", "V6"]
MEASURES = ["DTW", "In_Population", "Out_Population"]
RESULT_PATHS = [
    "similarity_measure/results/dtw",
    "similarity_measure/results/In_Population",
    "similarity_measure/results/Out_Population",
]
# ids used for experiment 1 - produced by get_test_split.py
SAMPLE_IDS = [...]
OUTPUT_DIR = "website/similarity_comparison/data"

def load_best_match(path, query_id):
    df = pd.read_csv(f"{path}/{query_id}.csv", header=None)
    return df.loc[df[0] == query_id, 1].iloc[0]


def build_similarity_table(sample_ids, paths, measures):
    df = pd.DataFrame(index=sample_ids)
    df.index.name = "id"
    for measure, path in zip(measures, paths):
        df[measure] = {id_: load_best_match(path, id_) for id_ in sample_ids}
    return df


def fetch_ecg_dataframe(unique_ids):
    ecgs = get_ecg_signals(unique_ids.tolist(), filtered=True)
    rows = []
    for row in ecgs.itertuples(index=False):
        signal = remove_zero_padding(row.signal)
        entry = {"id": row.id}
        for i, lead in enumerate(LEADS):
            entry[lead] = signal[i]
        rows.append(entry)
    return pd.DataFrame(rows)


def shuffle_and_save(df_similarity: pd.DataFrame, df_ecg: pd.DataFrame, output_dir: str):
    """
    This function was generated by Sonnet 4.6
    """

    df_shuffled = df_similarity.sample(frac=1)
    shuffled_ids = df_shuffled.index.tolist()
    cols = df_shuffled.columns.tolist()

    shuffled_rows = []
    column_orders = []

    for i, (sample_id, row) in enumerate(df_shuffled.iterrows()):
        # randomly permute the 3 measures for this row
        perm = np.random.permutation(len(cols))
        shuffled_rows.append(row.values[perm])
        column_orders.append([cols[i] for i in perm])

        # build parquet: original ECG + the 3 comparison ECGs in shuffled order
        match_ids = row.values[perm]

        frames = [
            df_ecg[df_ecg["id"] == sample_id],
            *[df_ecg[df_ecg["id"] == mid] for mid in match_ids],
        ]
        pd.concat(frames, ignore_index=True).to_parquet(
            f"{output_dir}/{i}.parquet", engine="pyarrow", index=False
        )

    df_out = pd.DataFrame(shuffled_rows, index=shuffled_ids)
    df_out.index.name = "id"
    df_out.to_csv(f"{output_dir}/data_shuffled.csv")

    pd.DataFrame({"id": shuffled_ids, "column_order": column_orders}).to_csv(
        f"{output_dir}/mapping.csv", index=False
    )


def main():

    df_similarity = build_similarity_table(SAMPLE_IDS, RESULT_PATHS, MEASURES)
    df_similarity.to_csv("similarity_measure/results/summary.csv")

    all_ids = pd.unique(np.concatenate([df_similarity.values.ravel(), SAMPLE_IDS]))
    df_ecg = fetch_ecg_dataframe(all_ids)

    shuffle_and_save(df_similarity, df_ecg, OUTPUT_DIR)

if __name__ == "__main__":
    main()
