"""
This file gives an overview of the accuracy of the model "https://github.com/antonior92/automatic-ecg-diagnosis" used on the filtered PTB-XL dataset
"""

from database.db_connection import extract_data
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

cols_abn = ["1dAVb", "rbbb", "lbbb", "sb", "af", "st"]
cols = ["id", "1dAVb", "rbbb", "lbbb", "sb", "af", "st"]

def get_lables(dataset, patient_ids, tablename):

    if patient_ids is None:
        query = f"""Select "id", "1dAVb", rbbb, lbbb, sb, af, st
                    From "{dataset}".{tablename}
                """
        
        rows = extract_data(query)

    else:
        placeholders = ",".join(["%s"] * len(patient_ids))

        query = f"""
        Select "id", "1dAVb", rbbb, lbbb, sb, af, st
        FROM "{dataset}".{tablename}
        WHERE id IN ({placeholders})
        """
        
        rows = extract_data(query, patient_ids)

    return rows


def print_detailed_accuracy(name, df_matches):
    """
    This function was generated by Sonnet 4.6
    """
    total = len(df_matches)
    print(f"\n{'='*45}")
    print(f"  {name}: {total}")
    print(f"{'='*45}")

    if total == 0:
        print("  (none)")
        return

    df_matches = df_matches.copy()

    def row_label(row):
        active = [c for c in cols_abn if row[f"{c}_gold"] == 1]
        return " + ".join(active) if active else "Norm"

    df_matches["_label"] = df_matches.apply(row_label, axis=1)
    counts = df_matches["_label"].value_counts()

    print(f"  {'Diagnosis':<20} | {'Count':>5} | {'% of total':>10}")
    print(f"  {'-'*42}")

    for label, count in counts.items():
        print(f"  {label:<20} | {count:>5} | {100*count/total:>9.1f}%")

    print(f"  {'-'*42}")
    print(f"  {'Total':<20} | {total:>5} | {'100.0%':>10}")

def evaluate_predictions(dataset, ids):
    """
    This function was generated by GPT-5.3
    """

    gold = pd.DataFrame(get_lables(dataset=dataset, patient_ids=ids, tablename="gold_lable"), columns=cols)
    pred = pd.DataFrame(get_lables(dataset=dataset, patient_ids=ids, tablename="dnn_annotations"), columns=cols)

    df = gold.merge(pred, on="id", suffixes=("_gold", "_pred"))

    match_cols = []
    for c in cols_abn:
        df[f"{c}_match"] = df[f"{c}_gold"] == df[f"{c}_pred"]
        match_cols.append(f"{c}_match")

    df["all_equal"] = df[match_cols].all(axis=1)

    tp_cols = []
    for c in cols_abn:
        gold_c = f"{c}_gold"
        pred_c = f"{c}_pred"
        
        df[f"{c}_tp"] = (df[gold_c] == 1) & (df[pred_c] == 1)
        tp_cols.append(f"{c}_tp")
    df["partial_equal"] = df[tp_cols].any(axis=1) & ~df["all_equal"]

    # Results
    full_matches = df[df["all_equal"]]
    partial_matches = df[df["partial_equal"]]
    mismatches = df[~df["partial_equal"] & ~df["all_equal"]]
    
    print_detailed_accuracy("Full matches:", full_matches)
    print_detailed_accuracy("Partial matches:", partial_matches)
    print_detailed_accuracy("Miss matches:", mismatches)
    print("Full Accurency:", len(full_matches)/((len(full_matches)+len(partial_matches)+len(mismatches))))
    print("Part Accurency:", (len(full_matches)+len(partial_matches))/((len(full_matches)+len(partial_matches)+len(mismatches))))
    
    return full_matches, partial_matches, mismatches

def create_plot(dataset, ids):
    """
    This function was generated by GPT-5.3
    """

    abn_cols_gold = [f"{c}_gold" for c in cols_abn]
    full_matches, partial_matches, mismatches = evaluate_predictions(dataset, ids)

    def split(df):
        df = df.copy()
        is_normal = df[abn_cols_gold].sum(axis=1) == 0
        return is_normal.sum(), (~is_normal).sum()

    # counts
    full_n, full_a = split(full_matches)
    part_n, part_a = split(partial_matches)
    none_n, none_a = split(mismatches)

    values = [full_n, full_a, part_n, part_a, none_n, none_a]

    # colors = match type
    colors = [
        "#4C78A8", "#4C78A8",   # full
        "#F58518", "#F58518",   # partial
        "#E45756", "#E45756"    # no match
    ]

    # hatch = normal vs abnormal
    hatches = [
        ".", "///",   # full
        ".", "///",   # partial
        ".", "///"    # no match
    ]

    fig, ax = plt.subplots(figsize=(8, 8))

    wedges, _ = ax.pie(
        values,
        labels=None,
        colors=colors,
        startangle=90,
        wedgeprops=dict(edgecolor="black", linewidth=1)
    )

    # apply hatch patterns
    for w, h in zip(wedges, hatches):
        w.set_hatch(h)

    # -------------------------
    # LEGEND (match type colors)
    # -------------------------
    match_legend = [
        Patch(facecolor="#4C78A8", edgecolor="black", label="Full match"),
        Patch(facecolor="#F58518", edgecolor="black", label="Partial match"),
        Patch(facecolor="#E45756", edgecolor="black", label="No match"),
    ]

    # -------------------------
    # LEGEND (pattern meaning)
    # -------------------------
    pattern_legend = [
        Patch(facecolor="white", edgecolor="black", hatch=".", label="Normal"),
        Patch(facecolor="white", edgecolor="black", hatch="///", label="Abnormal"),
    ]

    legend1 = ax.legend(handles=match_legend, loc="upper left", title="Match Type")
    ax.add_artist(legend1)

    ax.legend(handles=pattern_legend, loc="upper right", title="Pattern")

    plt.title(f"Prediction Pie - {dataset.upper()}")
    plt.show()

if __name__ == '__main__':
    dataset = "ptb-xl"
    df = pd.read_csv("database/transform_and_load/ptb/datasets/filtered_ecg_experiment_2.csv")
    df = df[df["age"] <= 95]
    ids = df["ecg_id"].tolist()
    print("Total Length", len(ids))
    create_plot(dataset, ids)