"""
This file was generated by Sonnet 4.6
"""

import os
import math
import json
import plotly.graph_objects as go
from clinical_friction.helpers.load_parquets import load_case
from pathlib import Path
import plotly

PLOTLY_JS_PATH = os.path.join(os.path.dirname(plotly.__file__), "package_data", "plotly.min.js")
with open(PLOTLY_JS_PATH, "r", encoding="utf-8") as f:
    PLOTLY_JS = f.read()

# ── Config ────────────────────────────────────────────────────────────────────
CACHE_DIR = "data/cached_plots"
LEAD_NAMES = ["DI", "DII", "DIII", "aVR", "aVL", "aVF", "V1", "V2", "V3", "V4", "V5", "V6"]
SAMPLING_RATE = 500
MS_PER_SAMPLE = 1000 // SAMPLING_RATE


# ── Reuse your existing figure + HTML builders (copied here for standalone use) ─

def render_figure_json(lead: tuple, name: str, title: str) -> str:
    t_ms     = [i * MS_PER_SAMPLE for i in range(len(lead))]
    max_t_ms = (len(lead) - 1) * MS_PER_SAMPLE

    y_min = math.floor(min(lead) * 10) / 10 - 0.1
    y_max = math.ceil(max(lead)  * 10) / 10 + 0.1

    x_tick_vals  = list(range(0, max_t_ms + 1, 200))
    x_minor_vals = list(range(0, max_t_ms + 1, 40))
    y_major_vals = [round(v * 0.5, 1) for v in range(
        math.floor(y_min / 0.5), math.ceil(y_max / 0.5) + 1)]
    y_minor_vals = [round(v * 0.1, 1) for v in range(
        math.floor(y_min / 0.1), math.ceil(y_max / 0.1) + 1)]

    minor = "#2E1A0E"
    major = "#5C2E18"

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=t_ms, y=list(lead), mode="lines",
        line=dict(color="#00ff88", width=1.2),
        name=name, showlegend=False, hoverinfo="skip",
    ))
    fig.add_trace(go.Scatter(
        x=t_ms, y=list(lead), mode="markers",
        marker=dict(size=8, color="rgba(0,0,0,0)", line=dict(width=0)),
        showlegend=False, name="",
        hovertemplate="t = %{x} ms<br>V = %{y:.3f} mV<extra></extra>",
    ))
    fig.update_layout(
        font=dict(family="Open Sans, sans-serif", color="#a0a0a0", size=12),
        title=dict(
            text=f"<b>{name}</b>",
            font=dict(family="Open Sans, sans-serif", color="#ffffff", size=16),
            x=0.5, xanchor="center",
        ),
        annotations=[dict(
            text=f"<b>{title}</b>",
            xref="paper", yref="paper", x=0, y=1.12,
            showarrow=False,
            font=dict(color="#a0a0a0", size=14),
            xanchor="left",
        )],
        plot_bgcolor="#0e1117", paper_bgcolor="#0e1117",
        font_color="#a0a0a0", autosize=True,
        xaxis=dict(
            title=dict(text="Time (s)", standoff=15),
            range=[0, max_t_ms],
            zeroline=False, ticks="outside", ticklen=5,
            tickmode="array", tickvals=x_tick_vals,
            ticktext=[f"{v/1000:.1f}" for v in x_tick_vals],
            showgrid=True, gridcolor=major, gridwidth=1,
            minor=dict(tickvals=x_minor_vals, showgrid=True,
                       gridcolor=minor, gridwidth=0.5),
        ),
        yaxis=dict(
            title="Amplitude (mV)",
            range=[y_min, y_max],
            zeroline=False, ticks="outside", ticklen=5,
            tickmode="array", tickvals=y_major_vals,
            ticktext=[f"{v:.1f}" for v in y_major_vals],
            showgrid=True, gridcolor=major, gridwidth=1,
            minor=dict(tickvals=y_minor_vals, showgrid=True,
                       gridcolor=minor, gridwidth=0.5),
        ),
        height=300,
        margin=dict(l=70, r=20, t=70, b=45),
    )
    return fig.to_json()


def make_chart_html(fig_json: str, key: str) -> str:
    return f"""<!DOCTYPE html>
<html><head>
<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
<style>
    * {{ margin:0; padding:0; box-sizing:border-box; }}
    body {{ background:#0e1117; }}
    #plot-{key} {{ width:100%; height:320px; }}
    #loader-{key} {{
        position:fixed; inset:0;
        background:#0e1117;
        display:flex; align-items:center; justify-content:center;
        z-index:999;
    }}
    .pulse {{
        width:8px; height:8px; border-radius:50%; background:#00ff88;
        animation:pulse 1s ease-in-out infinite;
        margin: 0 3px;
    }}
    .pulse:nth-child(2) {{ animation-delay:.2s; }}
    .pulse:nth-child(3) {{ animation-delay:.4s; }}
    @keyframes pulse {{
        0%,100% {{ opacity:.2; transform:scale(1); }}
        50%      {{ opacity:1;  transform:scale(1.4); }}
    }}
</style>
</head><body>
<div id="loader-{key}">
    <div class="pulse"></div>
    <div class="pulse"></div>
    <div class="pulse"></div>
</div>
<div id="plot-{key}"></div>
<script>
document.addEventListener('DOMContentLoaded', function() {{
    (function() {{
    var fig  = {fig_json};
    var base = JSON.parse(JSON.stringify(fig.data));
    var lay  = fig.layout;
    var el   = document.getElementById('plot-{key}');
    var sel  = [];
    var COLORS = ['#FFD700', '#FF6B6B'];

    Plotly.newPlot(el, fig.data, lay, {{responsive: true}}).then(function() {{
        document.getElementById('loader-{key}').style.display = 'none';
    }});

    el.on('plotly_click', function(data) {{
        var pt  = data.points[0];
        if (pt.curveNumber > 1) return;
        var px  = pt.x, py = pt.y;
        var idx = sel.findIndex(function(p) {{ return p.x === px; }});
        if      (idx >= 0)       sel.splice(idx, 1);
        else if (sel.length < 2) sel.push({{ x: px, y: py }});
        else                     sel = [sel[1], {{ x: px, y: py }}];
        redraw();
    }});

    function redraw() {{
        var ov  = [];
        var ann = [];
        sel.forEach(function(pt, i) {{
            ov.push({{
                type: 'scatter', mode: 'markers+text',
                x: [pt.x], y: [pt.y],
                marker: {{ color: COLORS[i], size: 14, symbol: 'circle',
                        line: {{ color: 'white', width: 1.5 }} }},
                text: ['P' + (i + 1)],
                textposition: 'top center',
                textfont: {{ color: COLORS[i], size: 12, family: 'monospace' }},
                showlegend: false, hoverinfo: 'skip'
            }});
        }});
        if (sel.length === 2) {{
            var p1 = sel[0], p2 = sel[1];
            var dt = Math.abs(p2.x - p1.x);
            ov.push({{
                type: 'scatter', mode: 'lines',
                x: [p1.x, p2.x], y: [p1.y, p2.y],
                line: {{ color: 'rgba(255,255,255,0.3)', width: 1, dash: 'dot' }},
                showlegend: false, hoverinfo: 'skip'
            }});
            ann.push({{
                x: (p1.x + p2.x) / 2,
                yshift: 20,
                text: '<b>\u0394t\u00a0=\u00a0' + dt + '\u00a0ms</b>',
                showarrow: false,
                font: {{ color: '#FFD700', size: 11 }},
                bgcolor: 'rgba(14,17,23,0.85)',
                bordercolor: 'rgba(255,215,0,0.55)',
                borderwidth: 1, borderpad: 4
            }});
        }}
        Plotly.react(el, base.concat(ov),
            Object.assign({{}}, lay, {{ annotations: ann }}),
            {{ responsive: true }}
        );
    }}
    }})();
}});
</script>
</body></html>
"""


# ── Main prerender logic ──────────────────────────────────────────────────────

def prerender_ecg(ecg: list,  title: str, data_id, patient_idx, info, dst: Path) -> None:
    """
    Render all 12 leads of one ECG to HTML files.

    Args:
        ecg:     list of 12 leads, each a list/array of float samples
        ecg_id:  unique identifier used as the folder name, e.g. "patient_007"
        title:   chart title shown top-left, e.g. "Patient ECG"
    """
    out = dst / str(data_id) / str(patient_idx) / str(info)
    out.mkdir(exist_ok=True, parents=True)
    #out = f"{data_id}/{patient_idx}/{info}"
    #out_dir = os.path.join(CACHE_DIR, out)
   # os.makedirs(out_dir, exist_ok=True)

    for i, (lead, name) in enumerate(zip(ecg, LEAD_NAMES)):
        fig_json = render_figure_json(tuple(lead), name, title)
        html     = make_chart_html(fig_json, f"lead_{i}")
        path     = out / f"lead_{i}.html"
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        #print(f"  wrote {path}")


def prerender_all(ecg_patient: list, ecg_reference: list| None, data_id, patient_idx, dst: Path) -> None:
    """
    Pre-bake both the patient ECG and the reference ECG.
    Call this whenever your data changes.
    """
    #print("Pre-rendering patient ECG…")
    prerender_ecg(ecg_patient,   title="Patient ECG", data_id= data_id, patient_idx=patient_idx,info= "patient", dst=dst)

    #print("Pre-rendering reference ECG…")
    if ecg_reference is not None:
        prerender_ecg(ecg_reference, title="Similar ECG", data_id=data_id, patient_idx=patient_idx, info="reference", dst=dst)
    #print("Done — all files written to", dst)




if __name__ == "__main__":

    for dataset in range(8):
        for case in range(20):
            data = load_case(dataset, case, prerender = True)

            prerender_all(data["ecg"], data["ecg_ref"], dataset, case)
