import pandas as pd
import numpy as np
import io
import pickle
import streamlit as st

def bytes_to_ecg(b: bytes) -> np.ndarray:
    """
    This function was generated by Sonnet 4.6
    """
    return np.load(io.BytesIO(b))

def bytes_to_list(b: bytes) -> list:
    """
    This function was generated by Sonnet 4.6
    """
    return pickle.loads(b)

def load_case(user, index, prerender = False):
    if prerender:
        dataset = user
    else:
        dataset = user.split("_")[-1]
    
    df = pd.read_parquet(f"data/{dataset}/{index}.parquet", engine="pyarrow")
    row = df.iloc[0]

    result = {
        "study_arm":  row["study_arm"],
        "age":        row["age"],
        "gender":     row["gender"],
        "prediction": bytes_to_list(row["prediction"]) if row["prediction"] is not None else None,
        "certainty": bytes_to_list(row["certainty"]) if row["certainty"] is not None else None,
        "ecg":      bytes_to_ecg(row["ecg"]),
        "age_ref":        row["age_ref"],
        "gender_ref":     row["gender_ref"],
        "ecg_ref":      bytes_to_ecg(row["ecg_ref"]) if row["ecg_ref"] is not None else None,
        "diagnosis_ref": bytes_to_list(row["diagnosis_ref"]) if row["diagnosis_ref"] is not None else None
    }

    return result



