import csv
import os
from pathlib import Path
import time
from collections import Counter

import dotenv
import streamlit as st
import streamlit.components.v1 as components
from components.ranking import ranking_section
from components.recorder import recorder_button, stop_recording
from components.signal_comparison import comparison_per_lead, display_summary
from components.state import get_resume_state


dotenv.load_dotenv()

required_vars = ["FLOCHALLENGE", "FLO_RESULTS", "FLO_FLASK_BASE"]

for var in required_vars:
    if var not in os.environ:
        raise RuntimeError(f"Variable {var} not found in environment variables!")

# Heart Emoij from: https://emojipedia.org/anatomical-heart
st.set_page_config(
    page_title="ECG Viewer", page_icon="🫀", layout="wide", initial_sidebar_state="collapsed"
)

root = Path(os.environ["FLO_RESULTS"]) / "results"
root.mkdir(exist_ok=True, parents=True)

if not st.user.is_logged_in:
    st.markdown(
        """
        <style>
        div.stButton > button {
            display: block;
            margin: 0 auto;
            width: 200px;
            height: 50px;
            font-size: 20px;
        }
        </style>
    """,
        unsafe_allow_html=True,
    )

    st.title("Welcome to the ECG Viewer 🫀")
    st.write("Please press the button below to log in.")

    if st.button("Log in"):
        st.login()
    st.stop()

if st.user.is_logged_in:
    user = st.user.get("preferred_username")
    
    idxes = list(range(24))

    if "page" not in st.session_state:
        page, index = get_resume_state(user, len(idxes))
        st.session_state.page = page
        st.session_state.page_index = index

    if "page_index" not in st.session_state:
        st.session_state.page_index = 0

    # Introduction Page
    if st.session_state.page == "start":
        st.title("Introduction - Similarity Measure Experiment 🫀")
        st.header("Background Information")
        text_background = """This experiment is designed to evaluate which of three similarity measures performs best. The methods being compared are:
                        <ul style="padding-left: 40px;">
                        <li> Multivariate Dynamic Time Warping (DTW): compares raw sequences by aligning them directly in the time domain. </li>
                        <li> Embeddings + Cosine Similarity: compares learned representations of the signal produced by a neural network. </li>
                        <li> Embeddings (alternative deep learning model) + Cosine Similarity: compares signal representations generated by a different neural network architecture. </li>
                        </ul>
                        The ECG signals that will be displayed are either without findings or display one of the following abnormalities: 1st degree atrioventricular block or Left bundle branch block.
                        <b>The order of the comparison signals is randomized between pages; the comparison number does NOT reflect the similarity method used. </b>
                        """
        #st.markdown(f'<p style="font-size: 20px;">{text_background}</p>', unsafe_allow_html=True)
        st.markdown(f'<div style="font-size: 20px;">{text_background}</div>', unsafe_allow_html=True)
        st.write("")
        st.header("Task Explanation")
        text_explanation = """For the experiment, the original signal and its comparisons are grouped by their 12 leads (DI - V6). Each lead is wrapped within an expender that can be collapsed for better overview. 
                                The compact version of the expender shows you all 4 signals for each lead at the same time, if you wanna see the signals in more detail enable the "Detailed View" toggle on the top left. This will span each signal over the whole width of the screen.  
                                <b> Your task will be to rank which of the three comparison signals is most similar to the original signal. </b>
                                After every expender you can indicate via buttons which of the 3 comparison signals was most similar to the original signal.
                                At the bottom of the screen, you can use the “Refresh Summary” button to calculate how often each comparison signal was selected as the most similar match for a lead. 
                                This is only meant as a helpful guide, so you do not have to use it.
                                You will also find a ranking panel at the bottom where you need to order the comparison signals based on how similar they are to the original signal. Once you are satisfied with your ranking, click the "Save" button.
                                To proceed to the next example, click the "Next" button on the right. In the bottom-left corner, you can track how many ECGs you have completed. In total, you will evaluate 24 ECGs.
                                <b>Please note that you cannot return to previous examples, so make sure your ranking is final before continuing.</b> <br>
                                If you accidentally close the window or wish to continue at a later time, you will be automatically redirected to your last unsaved ECG comparison after logging in again. Please note that in this case, the screen recording will need to be restarted.
                                To enable screen recording, click the "Screen Recording Settings" button and start recording as described in the privacy section below. """
        st.markdown(f'<p style="font-size: 20px;">{text_explanation}</p>', unsafe_allow_html=True)
        st.header("Privacy")
        text_privacy = """Before starting, we will ask you to indicate your level of expertise. We will also request your permission to record your screen for the purpose of analyzing interaction patterns, such as mouse movements.
                            To enable screen recording, click the "Screen Recording Settings" button below. This will open another window where you can select "Start recording", which triggers your browser to ask your permission to screen record and asks you to choose which screen or window to share.
                            <b>Please make sure to only start recording once per session.</b>
                            If you prefer not to have your screen recorded, the experiment can still be completed without screen recording. Simply do not press the recording button. <br>
                            No personal data will be collected, and all data will be handled confidentially."""
        st.markdown(f'<p style="font-size: 20px;">{text_privacy}</p>', unsafe_allow_html=True)

        
        recorder_button(user)

        st.header("Level of expertise")
        
        st.markdown(
                "<p style='font-size: 20px;'>What is your current position?</p>",
                unsafe_allow_html=True,
            )
        text_input = st.text_input(
            "", placeholder="e.g. Resident (Cardiology)", label_visibility="collapsed"
        )

        st.divider()

        st.markdown("""
        <style>
            [data-testid="stCheckbox"] p {
                font-weight: bold;
            }
        </style>
        """, unsafe_allow_html=True)
        

        col1, _, col3 = st.columns([6, 1, 1])


        with col1:

            consent_text = "I consent to the collection, use, and storage of data generated during this study, including my self-reported level of expertise, my responses to the signal comparison tasks, and, where applicable, screen recordings captured during the experiment. The findings derived from the collected data may be used in a master's thesis and in publications resulting from this research."
            agree = st.checkbox(f'{consent_text}')
            

        with col3:
           # <div style='margin-top: 4px;'></div>
            st.markdown(
                "<p style='font-size: 20px; margin-top: 4px;'</p>", unsafe_allow_html=True
            )
            if st.button(
                "Next →", type="primary", disabled=(not text_input.strip() or not agree), use_container_width=True
            ):

                user_path = root / str(user)
                user_path.mkdir(exist_ok=True, parents=True)
                file_path = user_path / f"responses_{user}.csv"

                file_exists = os.path.isfile(file_path)
                with open(file_path, "a", newline="") as f:
                    writer = csv.writer(f)
                    if not file_exists:
                        writer.writerow(["position"])
                    writer.writerow([text_input.strip()])

                st.session_state.page = "main"
                st.session_state.scroll_to_top = True
                st.rerun()

    # Comparison Tool
    if st.session_state.page == "main":
        
        if st.session_state.get("scroll_to_top"):
            # this component was generated by Sonnet 4.6
            components.html(
                f"""
                    <script>
                        setTimeout(function() {{
                            var el = window.parent.document.querySelector('section[data-testid="stMain"]');
                            if (el) {{
                                el.scrollTop = 0;
                            }}
                        }}, 200);
                    </script>
                    <!-- {time.time()} -->
                    """,
                height=0,
            )

            st.session_state.scroll_to_top = False

        if "ranking" not in st.session_state:
            st.session_state.ranking = ["Comparison 1", "Comparison 2", "Comparison 3"]
        if "ranking_saved" not in st.session_state:
            st.session_state.ranking_saved = False
        
        LEADS = ["DI", "DII", "DIII", "AVR", "AVL", "AVF", "V1", "V2", "V3", "V4", "V5", "V6"]
        for lead in LEADS:
            if f"saved_{lead}" not in st.session_state:
                st.session_state[f"saved_{lead}"] = None

        _, rec_col = st.columns([3, 1])
        with rec_col:
            recorder_button(user)

        st.markdown(
            "<h1 style='text-align: center;'>Similarity Measure Comparison</h1>",
            unsafe_allow_html=True,
        )

        comparison_per_lead()

        st.divider()
        st.markdown(
            "<h3 style='text-align:center;'>Rank the comparison signals based on their similarity to the original ECG signal.</h3>",
            unsafe_allow_html=True,
        )
        st.markdown(
            "<p style='text-align:center; color:gray;'>Drag and drop to reorder (1 = best match, 3 = worst match)</p>",
            unsafe_allow_html=True,
        )

        _, rank_col, col_3 = st.columns([1, 2, 1])
        with rank_col:
            ranking_section()
        with col_3:
            with st.container(border=True):
                display_summary()

        if st.session_state.ranking_saved:
            st.success(f"Ranking saved! ECG {st.session_state.page_index + 1} of {len(idxes)}")

        st.divider()

        _, _, col3 = st.columns([1, 3, 1])

        with col3:
            is_last = st.session_state.page_index == len(idxes) - 1

            if is_last:
                if st.button(
                    "Finish",
                    disabled=not st.session_state.ranking_saved,
                    type="primary",
                ):
                    st.session_state.page = "submitted"
                    st.rerun()
            else:
                if st.button(
                    "Next →",
                    disabled=not st.session_state.ranking_saved,
                ):
                    st.session_state.page_index += 1
                    st.session_state.comparison_index = 1
                    st.session_state.ranking = ["Comparison 1", "Comparison 2", "Comparison 3"]
                    st.session_state.ranking_saved = False
                    st.session_state.scroll_to_top = True
                    for lead in LEADS:
                        st.session_state[f"saved_{lead}"] = None
                    st.rerun()

        st.caption(f"ECG {st.session_state.page_index + 1} of {len(idxes)}")

    # Submission Page
    if st.session_state.page == "submitted":
        stop_recording(user)

        st.success("Thank you! Your responses have been submitted.")
        if st.button("Log out"):
            st.logout()
