"""
Parts of this file were generated by Sonnet 4.6
"""

import os
import pandas as pd
import streamlit as st

from pathlib import Path
import dotenv

dotenv.load_dotenv()

required_vars = ["FLO_RESULTS"]

for var in required_vars:
    if var not in os.environ:
        raise RuntimeError(f"Variable {var} not found in environment variables!")

root = Path(os.environ["FLO_RESULTS"]) / "results"
root.mkdir(exist_ok=True, parents=True)

def get_diagnosed_patients(diagnosis_csv):
    if not os.path.exists(diagnosis_csv):
        return set()
    df = pd.read_csv(diagnosis_csv)
    diagnosed = df[df["Selected"] == True]["Patient"].unique()
    return set(diagnosed)


CONDITION_MAP = {
    "norm": "Without findings",
    "1dAVb": "1st degree AV block (1dAVb)",
    "rbbb": "Right bundle branch block (RBBB)",
    "lbbb": "Left bundle branch block (LBBB)",
    "sb": "Sinus bradycardia (SB)",
    "af": "Atrial fibrillation (AF)",
    "st": "Sinus tachycardia (ST)",
}

CONDITION_KEYS = list(CONDITION_MAP.keys())
CONDITION_LABELS = list(CONDITION_MAP.values())

def save_diagnosis_csv(patient_index, diagnosis_csv):
    """Write current patient's selections into the CSV using abbreviations."""
    new_rows = pd.DataFrame({
        "Patient": patient_index,
        "Condition": CONDITION_KEYS,
        "Selected": [st.session_state.get(f"cb_{k}", False) for k in CONDITION_KEYS]
    })
    if os.path.exists(diagnosis_csv):
        df = pd.read_csv(diagnosis_csv)
        df = df[df["Patient"] != patient_index]
        df = pd.concat([df, new_rows], ignore_index=True)
    else:
        df = new_rows
    df.to_csv(diagnosis_csv, index=False)

def load_diagnosis_csv(patient_index, diagnosis_csv):
    if os.path.exists(diagnosis_csv):
        df = pd.read_csv(diagnosis_csv)
        patient_df = df[df["Patient"] == patient_index].set_index("Condition")
        if not patient_df.empty:
            return patient_df
    else:
        pd.DataFrame(columns=["Patient", "Condition", "Selected"]).to_csv(diagnosis_csv, index=False)
    return pd.DataFrame({"Selected": False}, index=CONDITION_KEYS)

@st.fragment
def diagnosis():
    user = st.user.get("preferred_username")
    diagnosis_csv = root / user / f"diagnosis_{user}.csv"
    st.header("Your Diagnosis")
    patient_index = st.session_state.patient_index

    if st.session_state.get("_last_diagnosis_patient") != patient_index:
        for k in CONDITION_KEYS:
            st.session_state.pop(f"cb_{k}", None)
        st.session_state["_last_diagnosis_patient"] = patient_index

    df = load_diagnosis_csv(patient_index, diagnosis_csv)

    for k in CONDITION_KEYS:
        if f"cb_{k}" not in st.session_state:
            st.session_state[f"cb_{k}"] = bool(df.loc[k, "Selected"]) if k in df.index else False

    cols = st.columns(3)
    for i, (k, label) in enumerate(CONDITION_MAP.items()):
        with cols[i % 3]:
            st.checkbox(
                label,
                key=f"cb_{k}",
                on_change=save_diagnosis_csv,
                args=(patient_index, diagnosis_csv,)
            )

    selected_keys = [k for k in CONDITION_KEYS if st.session_state.get(f"cb_{k}", False)]
    return selected_keys