import streamlit as st

def intro():
    st.header("Background Information")
    text_background = """This experiment is designed to evaluate how different forms of AI support influence diagnostic decision-making.
                    The experiment consists of four different setups, which are explained below:
                    <ul style="padding-left: 40px;">
                    <li> Baseline: diagnosis based on solily patient data (age, gender, 12 lead ECG). </li>
                    <li> Study Arm 1: diagnosis based on patient data in combination with an AI diagnostic prediction. </li>
                    <li> Study Arm 2: diagnosis based on patient data alongside the reference patient. </li>
                    <li> Study Arm 3: diagnosis based on patient data together with the AI prediction and the reference patient. </li>
                    </ul>
                    The AI-based predictions were produced by a deep neural network for ECG classification, which achieved an overall classification accuracy of 83%. <b>Please note that AI models are not perfect and may produce incorrect predictions.</b>
                    The reference patient is an individual whose ECG signal is most similar to that of the patient being assessed, according to the AI model's similarity analysis. <b>These similarity assessments are based on model parameters and should be interpreted as supportive information rather than definitive evidence.</b>
                    In the study arms including a reference patient, the age, gender, 12-lead ECG, and diagnosis of the reference patient will be displayed. The diagnosis of the reference patient is not generated by an AI model, but was annotated by a human doctor. 
                    All ECG signals used in this experiment were obtained from real human patients and were not AI-generated. Basic signal filtering was performed in accordance with standard ECG preprocessing practices.
                    The ECG signals shown in this experiment are either without findings or display one or multiple of the following abnormalities: 1st-degree atrioventricular block, left bundle branch block, right bundle branch block, 
                    sinus bradycardia, atrial fibrillation or sinus tachycardia.
                    """
    st.markdown(f'<div style="font-size: 20px;">{text_background}</div>', unsafe_allow_html=True)
    st.write("")
    st.header("Task Explanation")
    text_explanation = """For this experiment, you will diagnose 20 patients. Each page contains all relevant information for a single diagnosis. The different setups described above are distributed equally across the cases.
                            The structure of each page is the same. At the top of the page, you will see the age and gender of the current patient and, in some cases, the corresponding AI prediction. 
                            The AI's predictions are displayed in a table, showing the model's assessment for each abnormality. The abnormalities in the table are displayed as abbreviations. If you hover over them, a tooltip will appear showing the full name. The table also includes a consistency score, which reflects how stable the model's predictions were across five independent runs. A score of 100 indicates that the predictions were identical in all five runs, while lower scores indicate greater variation and therefore less certainty in the model's output.
                            If applicable, you will also see the age, gender, and diagnosis of the reference patient.
                            In the middle of the page, you will see the 12-lead ECG signal of the current patient and, if applicable, the reference patient. Using the three buttons, you can choose to view:
                            <ul style="padding-left: 40px;">
                                <li> the current patient's ECG in full length, </li>
                                <li> the reference ECG in full length, or </li>
                                <li> both ECGs side by side. </li>
                            </ul>
                            <b>As some diagnoses depend on the duration between specific ECG wave components, you can click on two points in the ECG plot and the time interval will be shown.</b> The plots also include grid lines along the x-axis at 0.2 s intervals. Be aware that sometimes it takes 1-2 seconds until the plots are loaded.
                            At the bottom of the page, you can enter your diagnosis by selecting the appropriate checkboxes. A patient may also present with multiple abnormalities. Your responses will be saved automatically. The sidebar on the left will indicate which patients you have already diagnosed.
                            If you are unsure about a diagnosis and would like to revisit the case later, you can flag the patient using the flag button in the top-left corner of the page.
                            To move to the next patient, use the arrow button at the bottom of the page or navigate through the sidebar. You can also revisit the experiment instructions through the sidebar at any time.
                            The sidebar is collapsible. To collapse or expand it, hover over the sidebar and click the highlighted arrows at the top.
                            The final stage of the experiment is a questionnaire that will be unlocked only after all patient diagnoses have been completed. Once all required sections have been completed, the submit button will become enabled. 
                            The diagnosis part of the study does not need to be completed in a single session, as all diagnosis data is saved immediately. You can return at any time and resume the diagnosis from where you left off. <b>Although patient diagnoses are saved automatically, questionnaire responses are only saved when you click the "Submit" button. Therefore, if you leave the questionnaire before submitting it, your responses will not be saved and you will need to complete the questionnaire again. 
                            </b> Please note that if you leave and return to the experiment, the screen recording will need to be restarted.
                            To enable screen recording, click the "Screen Recording Settings" button and start recording. """
    st.markdown(f'<div style="font-size: 20px;">{text_explanation}</div>', unsafe_allow_html=True)
    st.write("")
    
def privacy():    
    st.header("Privacy")
    text_privacy = """Before starting, we will ask you to indicate your level of expertise. We will also request your permission to record your screen for the purpose of analyzing interaction patterns, such as mouse movements.
                        To enable screen recording, click the "Screen Recording Settings" button on the introduction page (which you will see when you started the experiment). This will open another window where you can select "Start recording", which triggers your browser to ask your permission to screen record and asks you to choose which screen or window to share.
                        <b>Please make sure to only start recording once per session.</b>
                        If you prefer not to have your screen recorded, the experiment can still be completed without screen recording. Simply do not press the recording button. <br>
                        No personal data will be collected, and all data will be handled confidentially."""
    st.markdown(f'<p style="font-size: 20px;">{text_privacy}</p>', unsafe_allow_html=True)

def screenrecording():
    st.header("Screen Recording")
    text_privacy = """To enable screen recording, click the "Screen Recording Settings" button. This will open another window where you can select "Start recording", which triggers your browser to ask your permission to screen record and asks you to choose which screen or window to share.
                        <b>Please make sure to only start recording once per session.</b>
                        If you prefer not to have your screen recorded, the experiment can still be completed without screen recording. Simply do not press the recording button. <br>
                        """
    st.markdown(f'<p style="font-size: 20px;">{text_privacy}</p>', unsafe_allow_html=True)