import streamlit as st
import pandas as pd

mapping = {
    "NO_ABN": "Without findings",
    "1dAVb": "1st degree AV block",
    "RBBB": "Right bundle branch block",
    "LBBB": "Left bundle branch block",
    "SB": "Sinus bradycardia",
    "AF": "Atrial fibrillation",
    "ST": "Sinus tachycardia",
}

def predication_table(diagnosis, certainty):
    abn = ['1dAVb', 'rbbb', 'lbbb', 'sb', 'st', 'af']
    abn = [a.upper() for a in abn]
    df = pd.DataFrame({
        "Prediction": ["❌" if i == 0 else "✅" for i in diagnosis],
        "Prediction reliability": certainty
    }, index=abn).T

    df.index.name = None

    return df

def predication_table_hower(diagnosis, certainty):
    abn = ['1dAVb', 'RBBB', 'LBBB', 'SB', 'AF', 'ST']
    
    df = pd.DataFrame({
        "Prediction": ["❌" if i == 0 else "✅" for i in diagnosis],
        "Prediction reliability": certainty
    }, index=abn).T
    df.index.name = None
    
    column_config = {
        a: st.column_config.Column(help=mapping.get(a, a)) 
        for a in abn
    }
    
    return df, column_config

def predication_table_html(diagnosis, certainty):
    abn = ['1dAVb', 'RBBB', 'LBBB', 'SB', 'ST', 'AF']
    
    predictions = ["❌" if i == 0 else "✅" for i in diagnosis]

    # Build header row
    headers = "".join(
        f'<th title="{mapping.get(a, a)}" style="text-align:center; padding: 6px 12px; border: 1px solid #ddd; cursor:help;">{a}</th>'
        for a in abn
    )

    # Build prediction row
    pred_cells = "".join(
        f'<td title="{mapping.get(a, a)}" style="text-align:center; padding: 6px 12px; border: 1px solid #ddd; cursor:help;">{p}</td>'
        for a, p in zip(abn, predictions)
    )

    # Build certainty row
    cert_cells = "".join(
        f'<td title="{mapping.get(a, a)}" style="text-align:center; padding: 6px 12px; border: 1px solid #ddd; cursor:help;">{c}%</td>'
        for a, c in zip(abn, certainty)
    )

    html = f"""
    <table style="width:100%; border-collapse: collapse; font-size: 0.9rem;">
        <thead>
            <tr style="background-color: #f5f5f5;">
                <th style="text-align:left; padding: 6px 12px; border: 1px solid #ddd;"></th>
                {headers}
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="font-weight:600; padding: 6px 12px; border: 1px solid #ddd;">Prediction</td>
                {pred_cells}
            </tr>
            <tr style="background-color: #f9f9f9;">
                <td style="font-weight:600; padding: 6px 12px; border: 1px solid #ddd;">Reliability</td>
                {cert_cells}
            </tr>
        </tbody>
    </table>
    """
    return html

def record(title, gender, age, diagnosis = None, isPrediction = False, certainty = None):
    """
    The HTML part of this function was generated by Sonnet 4.6
    """

    dia_name = "Diagnosis"
    if isPrediction == True:
        dia_name = "AI Prediction + Certainty"


    if diagnosis is not None:
        if isPrediction == False:
            labels = " · ".join(mapping[p] for p in diagnosis)
            prediction_html = f"""
            <p style="font-weight: 600; margin: 0 0 0.2rem 0; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em; color: #666;">{dia_name}</p>
            <p style="margin: 0; font-size: 1rem;">{labels}</p>
            """
        else:
            prediction_html = f"""
            <p style="font-weight: 600; margin: 0 0 0.2rem 0; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em; color: #666;">{dia_name}</p>
            """
    else:
        prediction_html = ""

    gender = gender.capitalize()

    with st.container(border=True):
        st.markdown(f"""
            <p style="font-weight: 700; margin: 0 0 1rem 0; font-size: 1rem; text-align: center;">{title}</p>
            <hr style="margin: 0 0 1rem 0; border: none; border-top: 1px solid #ddd;">
            <p style="font-weight: 600; margin: 0 0 0.2rem 0; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em; color: #666;">Age</p>
            <p style="margin: 0 0 1rem 0; font-size: 1rem;">{age}</p>
            <p style="font-weight: 600; margin: 0 0 0.2rem 0; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em; color: #666;">Gender</p>
            <p style="margin: 0 0 1rem 0; font-size: 1rem;">{gender}</p>
            {prediction_html}
        """, unsafe_allow_html=True)

        if diagnosis is not None and isPrediction == True:
            # df = predication_table(diagnosis, certainty)
            # st.dataframe(df, hide_index=True, use_container_width=True)
            # html = predication_table_html(diagnosis, certainty)
            # st.markdown(html, unsafe_allow_html=True)
            df, column_config = predication_table_hower(diagnosis, certainty)
            st.dataframe(df, hide_index=True, use_container_width=True, column_config=column_config)