import streamlit.components.v1 as components
import time

def scroll_to_top():
    """
    This function was generated by Sonnet 4.6
    """
    components.html(
                f"""
                    <script>
                        setTimeout(function() {{
                            var el = window.parent.document.querySelector('section[data-testid="stMain"]');
                            if (el) {{
                                el.scrollTop = 0;
                            }}
                        }}, 200);
                    </script>
                    <!-- {time.time()} -->
                    """,
                height=0,
            )
