"""
The sidebar component was generated by Sonnet 4.6
"""

import streamlit as st
import os
from components.diagnosis import get_diagnosed_patients
from components.questionnaire import disable_questionnaire
import pandas as pd

from pathlib import Path
import dotenv

dotenv.load_dotenv()

required_vars = ["FLO_RESULTS"]

for var in required_vars:
    if var not in os.environ:
        raise RuntimeError(f"Variable {var} not found in environment variables!")

root = Path(os.environ["FLO_RESULTS"]) / "results"
root.mkdir(exist_ok=True, parents=True)

def init_sidebar_state():
    """Call this at the top of app.py before anything else."""
    if "current_section" not in st.session_state:
        st.session_state.current_section = "information"
    if "patient_index" not in st.session_state:
        st.session_state.patient_index = 0

def get_patient_label(i, name, diagnosed, flagged):
    """Flag takes priority over diagnosed checkmark."""
    if i in flagged:
        return f"{name}  🏳"
    if i in diagnosed:
        return f"{name}  ✓"
    return name

def sidebar(patient_keys):
    st.markdown("""
        <style>
        /* Sidebar open */
        section[data-testid="stSidebar"][aria-expanded="true"] {
            min-width: 180px !important;
            max-width: 180px !important;
            width: 180px !important;
        }

        /* Sidebar collapsed — let it shrink to zero */
        section[data-testid="stSidebar"][aria-expanded="false"] {
            min-width: 0 !important;
            max-width: 0 !important;
            width: 0 !important;
        }

        /* Main content always fills remaining space */
        section[data-testid="stMain"] {
            transition: margin-left 0.3s ease;
        }
        section[data-testid="stSidebar"][aria-expanded="false"] ~ section[data-testid="stMain"] {
            margin-left: 0 !important;
        }

        /* rest of your existing styles ... */
        div[data-testid="stSidebar"] .stButton {
            margin: 0 0 0.2rem 0 !important;
            padding: 0 !important;
        }
        div[data-testid="stSidebar"] .stButton button {
            border-radius: 8px !important;
            text-align: left !important;
            font-size: 0.9rem !important;
            font-weight: 400 !important;
            line-height: 1.4 !important;
            padding: 0.5rem 0.75rem !important;
            width: 100% !important;
            border: none !important;
            box-shadow: none !important;
        }
        div[data-testid="stSidebar"] [data-testid="baseButton-secondary"] {
            background: transparent !important;
            color: #444 !important;
        }
        div[data-testid="stSidebar"] [data-testid="baseButton-secondary"]:hover {
            background: #f0f0f0 !important;
            color: #111 !important;
        }
        div[data-testid="stSidebar"] [data-testid="baseButton-primary"] {
            background: #111 !important;
            color: #fff !important;
            font-weight: 600 !important;
        }
        .sidebar-header {
            font-size: 1.1rem;
            font-weight: 700;
            margin: 1rem 0 0.4rem 0;
            padding: 0 0.2rem;
        }
        </style>
        """, unsafe_allow_html=True)

    # Introduction
    st.sidebar.markdown("<p class='sidebar-header'>Introduction</p>", unsafe_allow_html=True)
    info_active = st.session_state.current_section == "information"
    if st.sidebar.button("Introduction", key="nav_info", use_container_width=True,
                          type="primary" if info_active else "secondary"):
        st.session_state.current_section = "information"
        st.rerun()

    # Patients
    user = st.user.get("preferred_username")
    diagnosis_csv = root / user / f"diagnosis_{user}.csv"
    diagnosed = get_diagnosed_patients(diagnosis_csv)
    flagged = st.session_state.get("flagged_patients", set())

    st.sidebar.markdown("<p class='sidebar-header'>Patients</p>", unsafe_allow_html=True)
    for i, name in enumerate(patient_keys):
        is_active = st.session_state.current_section == "patient" and st.session_state.patient_index == i
        label = get_patient_label(i, name, diagnosed, flagged)
        if st.sidebar.button(label, key=f"nav_patient_{i}", use_container_width=True,
                              type="primary" if is_active else "secondary"):
            st.session_state.current_section = "patient"
            st.session_state.patient_index = i
            st.session_state.scroll_to_top = True
            st.rerun()

    # Questionnaire
    st.sidebar.markdown("<p class='sidebar-header'>Questionnaire</p>", unsafe_allow_html=True)
    q_active = st.session_state.current_section == "questionnaire"
    patient_count = len(patient_keys)
    disable = disable_questionnaire(root, user, patient_count)
    if st.sidebar.button("Questionnaire", key="nav_questionnaire", use_container_width=True,
                          type="primary" if q_active else "secondary", disabled=disable):
        st.session_state.current_section = "questionnaire"
        st.rerun()