[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
issuer = "https://auth.your.domain"
client_id = "your_id"
client_secret = "your_secret"
cookie_secret ="your_secret"
server_metadata_url = "https://auth.your.domain/.well-known/openid-configuration"
expose_tokens = "id"
